export enum Keyword {
  Function = "fn",
  Object = "object",
  Do = "do",
  VariableConstant = "const",
  VariableMutable = "mutable",
  BooleanTrue = "true",
  BooleanFalse = "false",
  OperatorAddition = "+",
  OperatorSubstraction = "-",
  OperatorMultiplication = "*",
  OperatorDivision = "/",
  OperatorModulo = "%",
  OperatorBinaryAnd = "&",
  OperatorBinaryOr = "|",
}
